blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://chat.vuejs.org/
    about: For simple beginner questions, you can get quick answers from `#vue-i18n` channel of Discord
  - name: Questions & Discussions
    url: https://github.com/intlify/vue-i18n-next/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
